[tool.poetry]
name = "layouting"
version = "0.1.0"
description = ""
authors = ["rishs112 <rishs.112@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
